server:
  port: 8020

spring:
  application:
   name: main-EsAndCanel
  
  #es  
  data:
   elasticsearch:
    cluster-name: docker_es  #节点名字，默认elasticsearch
    cluster-nodes: 139.224.112.25:9300  #节点地址，多个节点用逗号隔开
    repositories:
     enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    